import { Layout } from "@/components/Layout";
import { Download } from "lucide-react";

const posts = [
  { file: "/posts/post-01-seguranca.jpg", title: "Segurança de Ponta a Ponta", caption: "🔒 Segurança não é luxo — é necessidade. E na era digital, uma única brecha pode comprometer toda a sua operação.\n\nNa Haliae, protegemos sua rede em todas as camadas com uma abordagem integrada e personalizada:\n\n✅ Firewalls de última geração com inspeção profunda de tráfego\n✅ Políticas de acesso rigorosas e segmentação de rede\n✅ Criptografia de dados em trânsito e em repouso\n✅ Monitoramento contínuo com resposta a incidentes\n✅ Gestão de vulnerabilidades e compliance\n\nSegundo o relatório da IBM, o custo médio de uma violação de dados em 2024 foi de US$ 4,88 milhões. Não espere um incidente para agir.\n\n📩 Fale com nossos especialistas e blindem sua operação hoje mesmo.\n\n🔗 Link na bio\n\n#Cibersegurança #RedeSegura #SegurançaDaInformação #Firewall #ProteçãoDeDados #TI #Haliae #InfraestruturaDeTI #DataProtection #InfoSec" },
  { file: "/posts/post-02-disponibilidade.jpg", title: "Alta Disponibilidade", caption: "⚡ Quanto custa 1 hora da sua empresa parada? E se fossem 8 horas? Um dia inteiro?\n\nSegundo o Gartner, o custo médio de downtime é de US$ 5.600 por minuto. Para muitas empresas, isso significa prejuízo financeiro, perda de clientes e danos à reputação.\n\nCom as soluções de Alta Disponibilidade da Haliae, sua operação nunca para:\n\n✅ Redundância ativa em todos os níveis da infraestrutura\n✅ Balanceamento de carga inteligente e dinâmico\n✅ Failover automático com comutação em milissegundos\n✅ Clusters de alta disponibilidade para serviços críticos\n✅ SLA de uptime de até 99,99%\n\nSua empresa funcionando 24/7/365, sem surpresas e sem desculpas.\n\n📩 Solicite uma análise gratuita da sua infraestrutura.\n\n🔗 Link na bio\n\n#AltaDisponibilidade #Uptime #Infraestrutura #TICorporativa #Redundância #Haliae #ContinuidadeDeNegócios #SemDowntime #HA #DisasterRecovery" },
  { file: "/posts/post-03-firewall.jpg", title: "Firewall de Próxima Geração", caption: "🛡️ Seu firewall ainda é do século passado? As ameaças evoluíram — sua proteção precisa acompanhar.\n\nFirewalls tradicionais apenas filtram portas e protocolos. Os firewalls de próxima geração (NGFW) da Haliae vão muito além:\n\n✅ Inspeção profunda de pacotes (DPI) em tempo real\n✅ Sistema de Prevenção de Intrusão (IPS) integrado\n✅ Controle granular de aplicações (Layer 7)\n✅ Filtragem avançada de conteúdo e URLs\n✅ Sandboxing para análise de ameaças zero-day\n✅ VPN integrada para acesso remoto seguro\n✅ Relatórios detalhados de tráfego e ameaças\n\nProteção inteligente que acompanha a evolução das ameaças cibernéticas, sem comprometer a performance da sua rede.\n\n📩 Agende uma demonstração gratuita.\n\n🔗 Link na bio\n\n#Firewall #NGFW #SegurançaDeRede #IPS #CyberSecurity #Haliae #ProteçãoAvançada #TI #DPI #ZeroDay" },
  { file: "/posts/post-04-monitoramento.jpg", title: "Monitoramento 24/7", caption: "📊 Você sabe exatamente o que está acontecendo na sua rede neste momento? Quais dispositivos estão sobrecarregados? Onde estão os gargalos?\n\nSe a resposta for \"não sei\", você está operando às cegas — e isso é um risco enorme.\n\nCom o monitoramento 24/7 da Haliae, você tem visibilidade total e controle absoluto:\n\n✅ Dashboards em tempo real com métricas críticas\n✅ Alertas inteligentes com escalação automática\n✅ Análise preditiva de performance e capacidade\n✅ Detecção proativa de falhas antes do impacto\n✅ Relatórios gerenciais e operacionais automatizados\n✅ NOC dedicado com equipe especializada\n\nProblemas resolvidos antes mesmo de impactarem seu negócio. Isso é monitoramento de verdade.\n\n📩 Quer ver como funciona? Solicite uma demo.\n\n🔗 Link na bio\n\n#NOC #Monitoramento #Monitoramento24x7 #GestãoDeRede #Haliae #Dashboard #AlertasInteligentes #TICorporativa #Observabilidade #NetworkOps" },
  { file: "/posts/post-05-pentest.jpg", title: "Pentest & Auditoria", caption: "🐛 Hackers não avisam quando vão atacar. Eles exploram silenciosamente as brechas que você nem sabe que existem.\n\nA pergunta não é SE sua empresa será atacada, mas QUANDO. E a melhor defesa é conhecer suas próprias vulnerabilidades antes dos atacantes.\n\nNossos serviços de Pentest e Auditoria de Segurança incluem:\n\n✅ Testes de intrusão externos e internos (Black Box, Grey Box, White Box)\n✅ Análise de vulnerabilidades em aplicações web e APIs\n✅ Avaliação de segurança em infraestrutura de rede\n✅ Engenharia social e simulação de phishing\n✅ Relatórios executivos e técnicos detalhados\n✅ Plano de remediação priorizado por criticidade\n✅ Reteste após correções implementadas\n\nSegurança de verdade se constrói com conhecimento. Saiba onde estão suas brechas.\n\n📩 Solicite um orçamento sem compromisso.\n\n🔗 Link na bio\n\n#Pentest #EthicalHacking #TesteDeIntrusão #AuditoriaDeTI #Vulnerabilidades #Haliae #SegurançaOfensiva #CyberSec #RedTeam #BugBounty" },
  { file: "/posts/post-06-sdwan.jpg", title: "SD-WAN & Conectividade", caption: "☁️ Sua empresa tem filiais? Operações remotas? Colaboradores em campo? Então você precisa de SD-WAN.\n\nLinks MPLS são caros e inflexíveis. A tecnologia SD-WAN da Haliae revoluciona sua conectividade WAN:\n\n✅ Roteamento inteligente baseado em políticas de aplicação\n✅ Priorização automática de tráfego crítico (VoIP, ERP, Cloud)\n✅ Uso simultâneo de múltiplos links (MPLS, banda larga, 4G/5G)\n✅ Redução de até 60% nos custos com conectividade\n✅ Criptografia ponta a ponta entre todas as localidades\n✅ Gestão centralizada via console única na nuvem\n✅ Deploy de novas filiais em minutos, não semanas\n\nPerformance de ponta para operações distribuídas, com total visibilidade e controle.\n\n📩 Descubra quanto sua empresa pode economizar com SD-WAN.\n\n🔗 Link na bio\n\n#SDWAN #Networking #RedeWAN #Conectividade #CloudNetworking #Haliae #TransformaçãoDigital #TI #WAN #NetworkOptimization" },
  { file: "/posts/post-07-failover.jpg", title: "Redundância & Failover", caption: "🔄 Zero downtime. Essa não é apenas uma promessa — é o que entregamos todos os dias para nossos clientes.\n\nEmpresas que dependem de tecnologia não podem se dar ao luxo de ficar offline. Com as soluções de failover da Haliae:\n\n✅ Comutação automática entre links em milissegundos\n✅ Redundância de equipamentos com hot standby\n✅ Monitoramento contínuo de saúde dos links\n✅ Balanceamento de carga entre múltiplos provedores\n✅ Planos de Disaster Recovery testados e documentados\n✅ RTO e RPO definidos conforme a criticidade do negócio\n\nRedundância não é gasto — é investimento em continuidade. Cada minuto de downtime custa dinheiro, reputação e confiança.\n\n📩 Vamos desenhar juntos seu plano de resiliência?\n\n🔗 Link na bio\n\n#Failover #Redundância #ZeroDowntime #AltaDisponibilidade #Haliae #InfraestruturaDeTI #Resiliência #BusinessContinuity #DR #DisasterRecovery" },
  { file: "/posts/post-08-pme.jpg", title: "Soluções para PMEs", caption: "🏢 Quem disse que infraestrutura de TI profissional é só para grandes corporações? Essa é uma das maiores mentiras do mercado.\n\nNa Haliae, acreditamos que toda empresa — independentemente do tamanho — merece tecnologia de ponta. Por isso criamos pacotes sob medida para PMEs:\n\n✅ Rede corporativa segura e estável\n✅ Firewall e antivírus gerenciados\n✅ Backup automatizado na nuvem\n✅ Suporte técnico especializado e humanizado\n✅ Monitoramento proativo da infraestrutura\n✅ Consultoria para crescimento escalável\n✅ Custo previsível com planos mensais acessíveis\n\nNão importa se você tem 5 ou 500 colaboradores. Sua empresa merece TI de verdade, com quem entende do assunto.\n\n📩 Peça uma proposta personalizada para sua empresa.\n\n🔗 Link na bio\n\n#PME #PequenasEmpresas #TIParaPME #InfraestruturaAcessível #Haliae #TecnologiaCorporativa #Negócios #Empreendedorismo #MPE #GestãoDeTI" },
  { file: "/posts/post-09-logistica.jpg", title: "Logística Conectada", caption: "🚛 No setor logístico, cada segundo conta. Uma falha de conectividade pode significar entregas atrasadas, mercadorias perdidas e clientes insatisfeitos.\n\nA Haliae entende os desafios únicos da logística e oferece soluções sob medida:\n\n✅ Conectividade robusta entre filiais e CDs\n✅ VPN site-to-site com alta disponibilidade\n✅ Integração com dispositivos IoT e sensores\n✅ Rastreamento de frota em tempo real\n✅ Comunicação unificada entre motoristas e base\n✅ Redundância de links para operação ininterrupta\n✅ Wi-Fi industrial para armazéns e pátios\n\nMais eficiência operacional, menos paradas não planejadas e total controle da cadeia logística.\n\n📩 Fale com nosso time especializado em logística.\n\n🔗 Link na bio\n\n#Logística #IoT #VPN #RastreamentoDeFroma #SupplyChain #Haliae #ConectividadeLogística #TecnologiaLogística #CentroDeDistribuição #LastMile" },
  { file: "/posts/post-10-parceria.jpg", title: "Parceiro Estratégico em TI", caption: "🤝 Não somos apenas mais um fornecedor de TI. Somos a extensão da sua equipe — o braço tecnológico que seu negócio precisa para crescer.\n\nA Haliae atua como parceiro estratégico de ponta a ponta:\n\n✅ Consultoria especializada em infraestrutura e segurança\n✅ Planejamento de capacidade e roadmap tecnológico\n✅ Implantação de projetos com metodologia ágil\n✅ Suporte contínuo com SLAs personalizados\n✅ Gestão proativa da infraestrutura\n✅ Relatórios gerenciais e reuniões periódicas de alinhamento\n✅ Evolução contínua da maturidade tecnológica\n\nDo planejamento à operação, estamos ao seu lado. Porque acreditamos que tecnologia boa é aquela que faz o negócio prosperar.\n\n📩 Vamos conversar sobre como podemos ajudar sua empresa?\n\n🔗 Link na bio\n\n#Parceria #ConsultoriaDeTI #TIEstratégica #Outsourcing #Haliae #TransformaçãoDigital #GestãoDeTI #ParceiroTecnológico #ManagedServices #ITSM" },
];

export default function Posts() {
  const handleDownload = (file: string, title: string) => {
    const link = document.createElement("a");
    link.href = file;
    link.download = `haliae-${title.toLowerCase().replace(/\s+/g, "-")}.jpg`;
    link.click();
  };

  return (
    <Layout>
      <div className="container py-16">
        <h1 className="text-3xl font-bold mb-2 text-center">Posts para <span className="text-gradient-cyan">Instagram</span></h1>
        <p className="text-muted-foreground text-center mb-10">Clique no botão para baixar cada imagem. As legendas sugeridas estão abaixo de cada post.</p>
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {posts.map((p) => (
            <div key={p.file} className="rounded-lg border border-border/50 bg-card/50 overflow-hidden">
              <img src={p.file} alt={p.title} className="w-full aspect-square object-cover" />
              <div className="p-4">
                <h3 className="font-semibold mb-1">{p.title}</h3>
                <p className="text-xs text-muted-foreground mb-3">{p.caption}</p>
                <button
                  onClick={() => handleDownload(p.file, p.title)}
                  className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground hover:shadow-lg hover:shadow-primary/20 transition-all"
                >
                  <Download className="h-3.5 w-3.5" /> Baixar Imagem
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </Layout>
  );
}
